### ISSUE TITLE
Viết đặc tả usecase

### ISSUE THREAD

**Issue by leanhnhandev** [leanhnhandev/talk-desk-java-spring-boot#8]
- [x] 1.   Viết đặc tả usecase - Đăng nhập (24/03/2023)
- [x] 2.   Viết đặc tả usecase - Đăng ký (25/03/2023)
- [x] 3.   Viết đặc tả usecase - Đăng xuất (26/03/2023)
- [x] 4.   Viết đặc tả usecase - Quên mật khẩu (27/03/2023)
- [x] 5.   Viết đặc tả usecase - Tìm kiếm (28/03/2023)
- [x] 6.   Viết đặc tả usecase - Quản lý tài khoản (28/03/2023)
- [x] 7.   Viết đặc tả usecase - Tạo yêu cầu hỗ trợ dịch vụ (29/03/2023) #16 
- [x] 8.   Viết đặc tả usecase - Đăng ký dịch vụ (30/03/2023) #16 
- [x] 9.   Viết đặc tả usecase - Hủy dịch vụ đăng ký (31/03/2023) #16 
- [x] 10. Viết đặc tả usecase - Đánh giá trải nghiệm dịch vụ (01/04/2023) #16 
- [x] 11. Viết đặc tả usecase - Xem lịch sử cuộc gọi (02/04/2023) #16 
- [x] 12. Viết đặc tả usecase - Xem báo cáo và phân tích (03/04/2023) #16 
- [x] 13. Viết đặc tả usecase - Quản lý người dùng (04/04/2023) #16 
- [x] 14. Viết đặc tả usecase - Quản lý dịch vụ (04/04/2023) #16 
- [x] 15. Viết đặc tả usecase - Quản lý báo cáo và phân tích (04/04/2023) #16

**Comment by leanhnhandev** [comment]
Hoàn thành Task 01 (24/03/2023)
https://docs.google.com/document/d/1B4WIdRYpXCG43WwIr_BKgHKoQfa-Tv_i/edit

**Comment by leanhnhandev** [comment]
Hoàn thành Task 02 (25/03/2023)
https://docs.google.com/document/d/14vGrmgs0uregXfUHznhUNGOTwMgC0oXb/edit

**Comment by leanhnhandev** [comment]
Hoàn thành Task 03 (26/03/2023)
https://docs.google.com/document/d/1-HdwtY27U5r1luX6uc6JeBm09gVBEqZc/edit

**Comment by leanhnhandev** [comment]
Hoàn thành Task 04 (27/03/2023)
https://docs.google.com/document/d/1_hQHsadgMdKomIPFgqiTns7PEhO4_Njz/edit

**Comment by leanhnhandev** [comment]
Hoàn thành Task 05 (28/03/2023)
https://docs.google.com/document/d/1b7ZcJFcH12zMvndQ8Yl2UO92XLuJBJzx/edit

**Comment by leanhnhandev** [comment]
Hoàn thành Task 06 (28/03/2023)
https://docs.google.com/document/d/1lLprcjC6FNdL_nN0wLv1qD3BwJkj1Ie1/edit

**Comment by leanhnhandev** [comment]
Hoàn thành Task 07 (29/03/2023)
https://docs.google.com/document/d/19El8dCaqQxKiu9W3cIG_0XFQelPSa8CB/edit

**Comment by leanhnhandev** [comment]
Hoàn thành Task 08 (30/03/2023)
https://docs.google.com/document/d/19El8dCaqQxKiu9W3cIG_0XFQelPSa8CB/edit

**Comment by leanhnhandev** [comment]
Hoàn thành Task 09 (31/03/2023)
https://docs.google.com/document/d/19El8dCaqQxKiu9W3cIG_0XFQelPSa8CB/edit

**Comment by leanhnhandev** [comment]
Hoàn thành Task 10 (01/04/2023)
https://docs.google.com/document/d/19El8dCaqQxKiu9W3cIG_0XFQelPSa8CB/edit

**Comment by leanhnhandev** [comment]
Hoàn thành Task 11 (02/04/2023)
https://docs.google.com/document/d/19El8dCaqQxKiu9W3cIG_0XFQelPSa8CB/edit

**Comment by leanhnhandev** [comment]
Hoàn thành Task 12 (03/04/2023)
https://docs.google.com/document/d/19El8dCaqQxKiu9W3cIG_0XFQelPSa8CB/edit

**Comment by leanhnhandev** [comment]
Hoàn thành Task 13 (04/04/2023)
https://docs.google.com/document/d/19El8dCaqQxKiu9W3cIG_0XFQelPSa8CB/edit

**Comment by leanhnhandev** [comment]
Hoàn thành Task 14 (04/04/2023)
https://docs.google.com/document/d/19El8dCaqQxKiu9W3cIG_0XFQelPSa8CB/edit

**Comment by leanhnhandev** [comment]
Hoàn thành Task 15 (04/04/2023)
https://docs.google.com/document/d/19El8dCaqQxKiu9W3cIG_0XFQelPSa8CB/edit
